I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: cn016
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1065] LD_LIBRARY_PATH: /home/apps/TENSORFLOW/1.0/gpu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PROTOBUF/3.1.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/MOCK/2.0.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/PBR/1.10.0/gnu/lib:/home/apps/PYTHONPACKAGES/2.7.10/FUNCSIGS/1.0.2/gnu/lib:/home/apps/BINUTILS/2.25/gnu/lib:/home/apps/LIBCUDNN/5.1.10/precompiled/lib:/home/soft/cuda-7.0/lib64:/home/soft/cuda-7.0/lib:/home/apps/PKGCONFIG/0.29/gnu//lib:/home/apps/GIT/2.9.0/gnu/lib:/home/apps/ZLIB/1.2.8/gnu/lib:/home/apps/PROTOBUF/3.1.0/gnu//lib:/home/soft/gcc-4.9.3/lib64:/home/soft/JDK/8.112/precompiled/lib:/home/soft/JDK/8.112/precompiled/jre/lib/:/home/soft/python-2.7.10/lib:/home/soft/intel2015/composer_xe_2015.3.187/compiler/lib/intel64:/home/soft/intel2015/composer_xe_2015.3.187/mkl/lib/intel64:/home/apps/HDF/5/1.8.16/gnu/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1066] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.0 locally
Using TensorFlow backend.
=>> PBS: job killed: walltime 9059 exceeded limit 9000
